kind: pipeline
type: docker
name: Nuget

steps:
- name: Build & Push
  image: mcr.microsoft.com/dotnet/sdk:6.0
  network_mode: bridge
  commands:
    - dotnet build -c Release
    - sh NugetBuild.sh
    - dotnet nuget push nupkgs/*.nupkg --api-key $NUGET_API_KEY --source  $NUGET_URI --skip-duplicate
  environment: 
    NUGET_API_KEY:
      from_secret: nuget_api_key
    NUGET_URI:
      from_secret: nuget_uri
